In [1]:
import numpy as np

# Buatlah array 2D berikut menggunakan numpy

arr = np.array([[4,4,5], 
                [7,6,4], 
                [9,7,4],
                [6,3,7]])

print(arr)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


In [2]:
# Buatlah array 3D berikut menggunakan numpy

arr = np.array([
[
[7,8,5],
[4,7,7],
[7,1,9],
[5,4,10]
],
[
[2,1,2],
[9,8,5],
[3,7,3],
[4,9,9]
],
[
[2,9,3],
[2,4,8],
[1,6,6],
[8,1,3]
]
])

print(arr)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


In [3]:
# Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. 
# kemudian tambahkan angka 
# 2 pada setiap bilangan di kolom genap array tersebut.

            #    0 1 2 3
arr = np.array([[1,8,8,2],  # 0
                [8,2,1,2],  # 1
                [10,1,4,7], # 2
                [1,4,7,8],  # 3
                [8,2,3,4]]) # 4

arr[1::2] += 1
arr[::,::2] += 2

print(arr)

[[ 3  8 10  2]
 [11  3  4  3]
 [12  1  6  7]
 [ 4  5 10  9]
 [10  2  5  4]]


In [ ]:
# Baliklah sumbu z array 3D berikut

arr = np.array([
[
[7,8,5],
[4,7,7],
[7,1,9],
[5,4,10]
],
[
[2,1,2],
[9,8,5],
[3,7,3],
[4,9,9]
],
[
[2,9,3],
[2,4,8],
[1,6,6],
[8,1,3] 
]
])

print(arr[::-1])

In [ ]:
# Ubahlah array pada soal e menjadi array 2D berukuran 6 x 6

arr = np.array([
[
[7,8,5],
[4,7,7],
[7,1,9],
[5,4,10]
],
[
[2,1,2],
[9,8,5],
[3,7,3],
[4,9,9]
],
[
[2,9,3],
[2,4,8],
[1,6,6],
[8,1,3] 
]
])

print(arr.reshape(6,6))

In [ ]:
arr = np.array([
    [ 5, 10, 10, 7],
    [ 7,  8, 4, 10],
    [ 9, 10, 2,  5],
    [ 1,  8, 9,  3],
    [ 6, 10, 5,  2],
    [ 4,  6, 9,  4]
])

arr[:3,[0,1]],arr[3:,[2,3]] = arr[3:,[2,3]],arr[:3,[0,1]]
arr[:3,[2,3]],arr[3:,[0,1]] = arr[3:,[0,1]],arr[:3,[2,3]]

print(arr)